### ISSUE TITLE
With mobile plugins are invisible

### ISSUE THREAD

**Issue by jeronath** [grazianobolla/espina#1]
First of all, thanks for your Espina theme which I now use on my https://jeronath.net/ site. I just needed to make some small modifications to adapt it to my needs!
However I notice a little problem: when I visit my site from a smartphone, and I suppose this will be the case for many Internet users, the two plugins I use, Categories + and Tags Plus do not appear and I do not understand why. I have to say I'm not very good at php... If you could help me to find the solution... Thanks in advance.

**Comment by grazianobolla** [comment]
Hi, I'm glad you found the theme useful.
The sidebar with the plugins will hide on mobile, this was done on purpose, there is no much space left for the sidebar, and putting the plugins at the bottom of the page was kind of weird for me.

If you want to keep the plugins, even on mobile (they will appear on the bottom of the page) go to `index.php` and under the comment that says `<!-- Content -->` replace:

```html
<div class="col-md-4 d-none d-md-block">
```
with:

```html
<div class="col-md-4">
```

It will tell bootstrap to not hide the sidebar. If you need anything else just tell me.
